CREATE TABLE wa_question
(
    wa_question_uid            bigint      NOT NULL,
    code_set_group_id          bigint,
    data_cd                    varchar(50),
    data_location              varchar(150),
    question_identifier        varchar(50) NOT NULL,
    question_oid               varchar(150),
    question_oid_system_txt    varchar(100),
    question_unit_identifier   varchar(20),
    data_type                  varchar(20),
    data_use_cd                varchar(20),
    question_label             varchar(300),
    question_tool_tip          varchar(2000),
    rdb_column_nm              varchar(30),
    part_type_cd               varchar(50),
    default_value              varchar(300),
    version_ctrl_nbr           int         NOT NULL,
    unit_parent_identifier     varchar(20),
    question_group_seq_nbr     int,
    future_date_ind_cd         char(1),
    legacy_data_location       varchar(150),
    repeats_ind_cd             char(1),
    add_user_id                bigint      NOT NULL,
    add_time                   timestamp    NOT NULL,
    last_chg_time              timestamp,
    last_chg_user_id           bigint,
    local_id                   varchar(50),
    question_nm                varchar(50),
    group_nm                   varchar(50),
    sub_group_nm               varchar(50),
    desc_txt                   varchar(2000),
    mask                       varchar(50),
    field_size                 varchar(10),
    rpt_admin_column_nm        varchar(50),
    nnd_msg_ind                char(1),
    question_identifier_nnd    varchar(50),
    question_label_nnd         varchar(150),
    question_required_nnd      char(1),
    question_data_type_nnd     varchar(10),
    hl7_segment_field          varchar(30),
    order_group_id             varchar(5),
    record_status_cd           varchar(20) NOT NULL,
    record_status_time         timestamp,
    nbs_ui_component_uid       bigint,
    standard_question_ind_cd   char(1),
    entry_method               varchar(20),
    question_type              varchar(20),
    admin_comment              varchar(2000),
    rdb_table_nm               varchar(30),
    user_defined_column_nm     varchar(30),
    min_value                  bigint,
    max_value                  bigint,
    standard_nnd_ind_cd        char(1),
    legacy_question_identifier varchar(50),
    unit_type_cd               varchar(20),
    unit_value                 varchar(50),
    other_value_ind_cd         char(1),
    source_nm                  varchar(250),
    coinfection_ind_cd         char(1),
    CONSTRAINT pk_wa_question PRIMARY KEY (wa_question_uid)
);

CREATE TABLE wa_template
(
    wa_template_uid bigint      NOT NULL,
    template_type   varchar(50) NOT NULL,
    xml_payload     varchar,
    publish_version_nbr   int,
    form_cd               varchar(50),
    condition_cd          varchar(20),
    bus_obj_type          varchar(50) NOT NULL,
    datamart_nm           varchar(21),
    record_status_cd      varchar(20) NOT NULL,
    record_status_time    timestamp    NOT NULL,
    last_chg_time         timestamp    NOT NULL,
    last_chg_user_id      bigint      NOT NULL,
    local_id              varchar(50),
    desc_txt              varchar(2000),
    template_nm           varchar(50),
    publish_ind_cd        char(1),
    add_time              timestamp    NOT NULL,
    add_user_id           bigint      NOT NULL,
    nnd_entity_identifier varchar(200),
    parent_template_uid   bigint,
    source_nm             varchar(250),
    template_version_nbr  int,
    version_note          varchar(2000),
    CONSTRAINT pk_wa_template PRIMARY KEY (wa_template_uid)
);

CREATE TABLE wa_ui_metadata
(
    wa_ui_metadata_uid        bigint NOT NULL,
    wa_template_uid           bigint NOT NULL,
    nbs_ui_component_uid      bigint NOT NULL,
    parent_uid                bigint,
    question_label            varchar(300),
    question_tool_tip         varchar(2000),
    enable_ind                varchar(1),
    default_value             varchar(300),
    display_ind               varchar(1),
    order_nbr                 int,
    required_ind              varchar(2),
    add_time                  timestamp,
    add_user_id               bigint,
    last_chg_time             timestamp,
    last_chg_user_id          bigint,
    record_status_cd          varchar(20),
    record_status_time        timestamp,
    max_length                bigint,
    admin_comment             varchar(2000),
    version_ctrl_nbr          int    NOT NULL,
    field_size                varchar(10),
    future_date_ind_cd        char(1),
    local_id                  varchar(50),
    code_set_group_id         bigint,
    data_cd                   varchar(50),
    data_location             varchar(150),
    data_type                 varchar(20),
    data_use_cd               varchar(20),
    legacy_data_location      varchar(150),
    part_type_cd              varchar(50),
    question_group_seq_nbr    int,
    question_identifier       varchar(50),
    question_oid              varchar(150),
    question_oid_system_txt   varchar(100),
    question_unit_identifier  varchar(20),
    repeats_ind_cd            char(1),
    unit_parent_identifier    varchar(20),
    group_nm                  varchar(50),
    sub_group_nm              varchar(50),
    desc_txt                  varchar(2000),
    mask                      varchar(50),
    entry_method              varchar(20),
    question_type             varchar(20),
    publish_ind_cd            char(1),
    min_value                 bigint,
    max_value                 bigint,
    standard_question_ind_cd  char(1),
    standard_nnd_ind_cd       char(1),
    question_nm               varchar(50),
    unit_type_cd              varchar(20),
    unit_value                varchar(50),
    other_value_ind_cd        char(1),
    batch_table_appear_ind_cd char(1),
    batch_table_header        varchar(50),
    batch_table_column_width  int,
    coinfection_ind_cd        char(1),
    block_nm                  varchar(30),
    CONSTRAINT pk_wa_ui_metadata PRIMARY KEY (wa_ui_metadata_uid)
);

CREATE TABLE wa_nnd_metadata
(
    wa_nnd_metadata_uid     bigint      NOT NULL,
    wa_template_uid         bigint      NOT NULL,
    question_identifier_nnd varchar(50),
    question_label_nnd      varchar(150),
    question_required_nnd   char(1)     NOT NULL,
    question_data_type_nnd  varchar(10) NOT NULL,
    hl7_segment_field       varchar(30) NOT NULL,
    order_group_id          varchar(5),
    translation_table_nm    varchar(30),
    add_time                timestamp    NOT NULL,
    add_user_id             bigint      NOT NULL,
    last_chg_time           timestamp    NOT NULL,
    last_chg_user_id        bigint      NOT NULL,
    record_status_cd        varchar(20) NOT NULL,
    record_status_time      timestamp    NOT NULL,
    question_identifier     varchar(50),
    xml_path                varchar(2000),
    xml_tag                 varchar(300),
    xml_data_type           varchar(50),
    part_type_cd            varchar(50),
    repeat_group_seq_nbr    int,
    question_order_nnd      int,
    local_id                varchar(50),
    wa_ui_metadata_uid      bigint      NOT NULL,
    question_map            varchar(2000),
    indicator_cd            varchar(2000),
    CONSTRAINT pk_wa_nnd_metadata PRIMARY KEY (wa_nnd_metadata_uid)
);

ALTER TABLE wa_nnd_metadata
    ADD CONSTRAINT FK_WA_NND_METADATA_ON_WA_TEMPLATE_UID
        FOREIGN KEY (wa_template_uid) REFERENCES wa_template (wa_template_uid);

ALTER TABLE wa_nnd_metadata
    ADD CONSTRAINT FK_WA_NND_METADATA_ON_WA_UI_METADATA_UID
        FOREIGN KEY (wa_ui_metadata_uid) REFERENCES wa_ui_metadata (wa_ui_metadata_uid);

ALTER TABLE wa_ui_metadata
    ADD CONSTRAINT FK_WA_UI_METADATA_ON_WA_TEMPLATE_UID
        FOREIGN KEY (wa_template_uid) REFERENCES wa_template (wa_template_uid);

CREATE TABLE code_value_general
(
    code_desc_txt           varchar(300),
    code_short_desc_txt     varchar(100),
    code_system_cd          varchar(300),
    code_system_desc_txt    varchar(100),
    effective_from_time     timestamp,
    effective_to_time       timestamp,
    indent_level_nbr        smallint,
    is_modifiable_ind       char(1),
    nbs_uid                 int,
    parent_is_cd            varchar(20),
    source_concept_id       varchar(20),
    super_code_set_nm       varchar(256),
    super_code              varchar(20),
    status_cd               char(1),
    status_time             timestamp,
    concept_type_cd         varchar(20),
    concept_code            varchar(256),
    concept_nm              varchar(256),
    concept_preferred_nm    varchar(256),
    concept_status_cd       varchar(256),
    concept_status_time     timestamp,
    code_system_version_nbr varchar(256),
    concept_order_nbr       int,
    admin_comments          varchar(2000),
    add_time                timestamp,
    add_user_id             bigint,
    code_set_nm             varchar(256) NOT NULL,
    code                    varchar(20)  NOT NULL,
    CONSTRAINT pk_code_value_general PRIMARY KEY (code_set_nm, code)
);

CREATE TABLE codeset
(
    assigning_authority_cd       varchar(199),
    assigning_authority_desc_txt varchar(100),
    code_set_desc_txt            varchar(2000),
    effective_from_time          timestamp,
    effective_to_time            timestamp,
    is_modifiable_ind            char(1),
    nbs_uid                      int,
    source_version_txt           varchar(20),
    source_domain_nm             varchar(50),
    status_cd                    varchar(1),
    status_to_time               timestamp,
    code_set_group_id            bigint,
    admin_comments               varchar(2000),
    value_set_nm                 varchar(256),
    ldf_picklist_ind_cd          char(1),
    value_set_code               varchar(256),
    value_set_type_cd            varchar(20),
    value_set_oid                varchar(256),
    value_set_status_cd          varchar(256),
    value_set_status_time        timestamp,
    parent_is_cd                 bigint,
    add_time                     timestamp,
    add_user_id                  bigint,
    class_cd                     varchar(30)  NOT NULL,
    code_set_nm                  varchar(256) NOT NULL,
    CONSTRAINT pk_codeset PRIMARY KEY (class_cd, code_set_nm)
);

CREATE TABLE codeset_group_metadata
(
    code_set_group_id       bigint       NOT NULL,
    code_set_nm             varchar(256) NOT NULL,
    vads_value_set_code     varchar(256),
    code_set_desc_txt       varchar(2000),
    code_set_short_desc_txt varchar(2000),
    ldf_picklist_ind_cd     char(1),
    phin_std_val_ind        char(1),
    CONSTRAINT pk_codeset_group_metadata PRIMARY KEY (code_set_group_id)
);

ALTER TABLE codeset
    ADD CONSTRAINT FK_CODESET_ON_CODE_SET_GROUP FOREIGN KEY (code_set_group_id) REFERENCES codeset_group_metadata (code_set_group_id);